### ISSUE TITLE
@googlecloud/compute module installation fails on NodeJS version upgrade.

### ISSUE THREAD

**Issue by jagadish-kb** [googleapis/nodejs-compute#216]
We are upgrading our NodeJS Version from v6.9.1 to v10.13.0 (Latest LTS). Our package.json has the below dependency:
`"@google-cloud/compute": "0.10.0"`
When trying to either install the modules or rebuild the modules we see errors where in native (c/c++) modules are rebuilt. PFB error trace:
```
npm install

> unix-dgram@0.2.3 install /var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/unix-dgram
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/unix-dgram/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/unix-dgram/.node-gyp'
gyp ERR! System Linux 4.4.0-137-generic
gyp ERR! command "/var/vcap/packages/node-v10.13.0-linux-x64/bin/node" "/var/vcap/packages/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/unix-dgram
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> grpc@1.8.4 install /var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.4 and node@10.13.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.4 and node@10.13.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
gypgyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/.node-gyp"
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gypgyp  WARN install got an error, rolling back install
ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/.node-gyp'
gyp ERR!gyp WARN  install got an error, rolling back install
System Linux 4.4.0-137-generic
gyp ERR!gyp  ERR! configure error
commandgyp  "/var/vcap/packages/node-v10.13.0-linux-x64/bin/node" "/var/vcap/packages/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/var/vcap/data/packages/servic$
-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/no$
e_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
ERR! stack Error: EACCES: permission denied, mkdir '/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/.node-gyp'
gyp ERR!gyp  cwdERR! System Linux 4.4.0-137-generic
 /var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! command "/var/vcap/packages/node-v10.13.0-linux-x64/bin/node" "/var/vcap/packages/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/var/vcap/data/packages/se
rvice-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f
6/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/var/vcap/packages/node-v10.13.0-linux-x64/bin/node /var/vcap/packages/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/var
/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6
224291b53f9152539f6/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.4.0-137-generic
node-pre-gyp ERR! command "/var/vcap/packages/node-v10.13.0-linux-x64/bin/node" "/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_libr
ary"
node-pre-gyp ERR! cwd /var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/var/vcap/packages/node-v10.13.0-linux-x64/bin/node /var/vcap/packages/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/var/vcap/data/packages/service-fab
rik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/var/vcap/data/packages/service-fabrik-broker/1e7bbea9bc9a9c8b1c7e6224291b53f9152539f6/node_module
s/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.3 (node_modules/unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.4 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.8.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-28T03_25_00_692Z-debug.log

```
PS: Instead of upgrading to v10.13.0, I tried the intermediate LTS version 8.14.0, it worked. And i suspect it worked because the npm manager was able to download the precompiled binary for grpc. 
`[grpc] Success: "/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote`
Complete console output with Node V8.14.0
```
# node --version
v8.14.0
broker/7f2349bd-66e3-402d-9016-30d574dab1a4:/var/vcap/packages/service-fabrik-broker# npm install

> unix-dgram@0.2.3 install /var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/unix-dgram
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/unix-dgram/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/unix-dgram/.node-gyp'
gyp ERR! System Linux 4.4.0-137-generic
gyp ERR! command "/var/vcap/packages/node-v8.14.0-linux-x64/bin/node" "/var/vcap/packages/node-v8.14.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/unix-dgram
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> grpc@1.8.4 install /var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote

> phantomjs-prebuilt@2.1.16 install /var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
/tmp/phantomjs is not writable: EACCES: permission denied, mkdir '/tmp/phantomjs'
/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/phantomjs-prebuilt/phantomjs is not writable: EACCES: permission denied, mkdir '/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node$
modules/phantomjs-prebuilt/phantomjs'
/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/phantomjs-prebuilt/tmp/phantomjs is not writable: EACCES: permission denied, mkdir '/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/$
ode_modules/phantomjs-prebuilt/tmp'
Can not find a writable tmp directory, please report issue on https://github.com/Medium/phantomjs/issues with as much information as possible.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.3 (node_modules/unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 (node_modules/phantomjs-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1238 packages from 1316 contributors and audited 5655 packages in 54.18s
found 107 vulnerabilities (19 low, 74 moderate, 13 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
broker/7f2349bd-66e3-402d-9016-30d574dab1a4:/var/vcap/packages/service-fabrik-broker# echo $?
0
```

Since v8.14.0 install does not result in an error, we are now planning to upgrade our node to this version, however would really like to understand and upgrade to the latest Node LTS version. Would appreciate if you can kindly provide your inputs on how we can make the above work.

#### Environment details

  - OS: Ubuntu 14.04.5 LTS, Trusty Tahr
  - Node.js version:10.13.0
  - npm version:64.1
  - `@google-cloud/compute` version: 0.10.0

#### Steps to reproduce

  1. Include the above version in package.json and run either `npm install` (fresh)`
 or 
  2. `npm rebuild` if upgrading from older version of nodejs to latest version of 10.13.0

**Comment by jagadish-kb** [comment]
@JustinBeckwith  I tested it once again on my local mac (High Sierra - 10.13.6) & even on our server Image (Ubuntu 14.04.5 LTS, Trusty Tahr) and on both, fresh install (rm -rf node_modules/ & npm install) is failing with the same error as mentioned in the above problem description (steps to reproduce section)

I think this is very specific to the OS image where we are running this as the native c libraries required for GRPC is being rebuilt by `node-gyp` and its failing at this stage. Also, as mentioned in the error 
```
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.4 and node@10.13.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
```
In case of Nodev8.14.0, the prebuilt binaries for grpc is available and hence installing this package with Node8 works. (`[grpc] Success: "/var/vcap/data/packages/service-fabrik-broker/bc673d0d31f2b7cc23dd70766c7379fb817ff844/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote`)


So can you please get the prebuilt binaries for grpc in at the above location? Then may be it would not build it locally and it will pass. This is my analysis based on the error messages as seen on the console.

**Comment by JustinBeckwith** [comment]
So this is especially weird :) This library doesn't pull in gRPC as a dependency.  I checked both 0.10, and 0.11 (which shipped this morning).  Can you reproduce this with *just* this library?  It's likely another one of our dependencies are actually causing this one.

**Comment by JustinBeckwith** [comment]
Greetings!  Without more information, sadly there's not much we can do with this issue.  If you are still having problems - please do let us know!
