### ISSUE TITLE
upgrading from `google-cloud` to `@google-cloud/compute` breaks auth on kubernetes

### ISSUE THREAD

**Issue by macrozone** [googleapis/nodejs-compute#370]
#### Environment details

  - OS: google cloud kubrnetes engine
  - Node.js version: 10.x
  - npm version:  
  - `@google-cloud/compute` version:   1.1.6

#### Steps to reproduce

we upgraded from `google-cloud` to `@google-cloud/compute` like this:

OLD:

```
const gcloud = require('google-cloud')
const gce = gcloud.compute()
const zone = gce.zone('europe-west1-d')
const disk = zone.disk("somediskname");
const [snapshot, operation, apiResponse] = await disk.createSnapshot(...);

```

NEW:

```
const Gce = require("@google-cloud/compute");
const gce = new Gce();
const zone = gce.zone("europe-west1-d");
const disk = zone.disk("somediskname");
const [snapshot, operation, apiResponse] = await disk.createSnapshot(...);

```

Now, when we deploy this application to kubernetes running on google-cloud, it will throw this error:

```
Error: Insufficient Permission: Request had insufficient authentication scopes.
    at new ApiError (/app/node_modules/@google-cloud/common/build/src/util.js:60:15)
    at Util.parseHttpRespBody (/app/node_modules/@google-cloud/common/build/src/util.js:195:38)
    at Util.handleResp (/app/node_modules/@google-cloud/common/build/src/util.js:136:117)
    at retryRequest (/app/node_modules/@google-cloud/common/build/src/util.js:431:22)
    at onResponse (/app/node_modules/retry-request/index.js:206:7)
    at /app/node_modules/teeny-request/build/src/index.js:233:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 403,
  errors:
   [ { domain: 'global',
       reason: 'insufficientPermissions',
       message:
        'Insufficient Permission: Request had insufficient authentication scopes.' } ],

```

whereas the old version successfully executed the api call

**Comment by macrozone** [comment]
ok actually it seems it has nothing to do with the upgrade, but rather we run into this issue: https://stackoverflow.com/a/58991707

and we had two node pools where the new one has missing permission. I had bad luck when i tested this, because my pod got scheduled on a new node when using the new api and failed there. When i reverted the change, it got scheduled on the old node by chance and was successful, so i wrongly assumed it had to do with the library 🤦‍♂
