### ISSUE TITLE
How to create a global address using this Node.js lib

### ISSUE THREAD

**Issue by Biga-incorta** [googleapis/nodejs-compute#533]
When I tried to create a global address, I know that I have to not set the region but it raises an error when I'm trying to do that.
```
const Compute = require('@google-cloud/compute');
const compute = new Compute();
const region = compute.region();

async function create(){
 try {
await region.createAddress('testgip', {
    ipVersion: "IPV6"
})
 } catch(e) {console.error(e)}

}

create();
```

```
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/compute/v1/projects/incortacloud/regions/addresses</code> was not found on this server.  <ins>That’s all we know.</ins>

    at Util.parseHttpRespBody (/home/incorta/cloud-server/server/node_modules/@google-cloud/common/build/src/util.js:188:42)
    at Util.handleResp (/home/incorta/cloud-server/server/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/home/incorta/cloud-server/server/node_modules/@google-cloud/common/build/src/util.js:432:22)
    at onResponse (/home/incorta/cloud-server/server/node_modules/retry-request/index.js:206:7)
    at /home/incorta/cloud-server/server/node_modules/teeny-request/build/src/index.js:233:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'Cannot parse response as JSON: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/compute/v1/projects/incortacloud/regions/addresses</code> was not found on this server.  <ins>That’s all we know.</ins>\n',
```

**Comment by sofisl** [comment]
Hi @Biga-incorta,

If you're trying to create a global address, you'll want to use the class `globalAddresses`:

```
compute.globalAddresses.insert({
      "project": PROJECT,
      "resource": {
        "name": NAME,
        "ipVersion": "IPV6"
      }
})
```

See [here](https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses/insert).
