### ISSUE TITLE
Some API calls fail to parse response and do not give useful error

### ISSUE THREAD

**Issue by HiroLord** [googleapis/nodejs-compute#66]
#### Environment details

  - OS: Mac OS 10.13.4
  - Node.js version: v8.10.0
  - npm version: 5.8.0
  - `@google-cloud/compute` version: 0.10.0

#### Steps to reproduce

  1. Create a snapshot ref using `compute -> zone -> disk -> snapshot`
  2. Attempt to `.get()` the snapshot details

Example:

	const Compute = require('@google-cloud/compute');
	const compute = new Compute();
	const zone = compute.zone('us-east1-b');
	const disk = zone.disk('a-real-disk');
	const snapshot = disk.snapshot('a-real-snapshot');
	snapshot.get()
	    .then(console.log).catch(console.error);

This will return the error 
```
{ ApiError: Error during request.
    at Object.parseHttpRespBody (/Users/pxt1842/workspace/cloud-function/node_modules/@google-cloud/common/src/util.js:195:32)
    at Object.handleResp (/Users/pxt1842/workspace/cloud-function/node_modules/@google-cloud/common/src/util.js:137:18)
    at /Users/pxt1842/workspace/cloud-function/node_modules/@google-cloud/common/src/util.js:504:12
    at Request.onResponse [as _callback] (/Users/pxt1842/workspace/cloud-function/node_modules/retry-request/index.js:195:7)
    at Request.self.callback (/Users/pxt1842/workspace/cloud-function/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/pxt1842/workspace/cloud-function/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
  code: undefined,
  errors: undefined,
  response: undefined,
  message: 'Error during request.' }
```
which does not tell us much at all about what went wrong. I went into `@google-cloud/common/src/util.js` and added some logs; turns out the response from the API call is the string `Not Found` which is then attempted to being parsed into JSON, which fails. This causes the error above. Note that the Disk and Snapshot I am using are both real and named correctly, yet I still get this error. However, using

    compute.snapshot('a-real-snapshot').get().then(...);

instead works fine.

**Comment by stephenplusplus** [comment]
I reproduced and will have a fix shortly.

**Comment by stephenplusplus** [comment]
PR sent: #67 

Thanks for reporting, @HiroLord!
