### ISSUE TITLE
bulkInsert with complex perInstanceProperties

### ISSUE THREAD

**Issue by austyh** [googleapis/nodejs-compute#765]
I am trying to create multiple instances with those params:
```
    const [response] = await instancesClient.bulkInsert({
        bulkInsertInstanceResourceResource: {
            count: 2,
            minCount: count: 2,
            perInstanceProperties,
            instanceProperties: {
                advancedMachineFeatures: {
                    enableNestedVirtualization: true
                },
```
perInstanceProperties looks like this:
```
  perInstanceProperties: {
    'tt-fd3c19b9-f1ab-4354-8dbd-903bb7334b0b-1': {},
    'tt-fd3c19b9-f1ab-4354-8dbd-903bb7334b0b-2': {}
  }
```

And i got error:
```
node_modules/google-gax/build/src/googleError.js:59
        const error = Object.assign(new GoogleError(json['error']['message']), proto3Error);
                                    ^

GoogleError: Invalid value for field 'resource.perInstanceProperties.key': ''. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
    at GoogleError.parseHttpError (/home/aust/workspace/rueda/splinter/node_modules/google-gax/build/src/googleError.js:59:37)
    at decodeResponse (/home/aust/workspace/rueda/splinter/node_modules/google-gax/build/src/fallbackRest.js:72:49)
    at /home/aust/workspace/rueda/splinter/node_modules/google-gax/build/src/fallbackServiceStub.js:90:42
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  details: [],
  code: 3
}
```

**Comment by sofisl** [comment]
Hi @austyh, I think your keys must be set to a property of the instance. If these are names, then it should look like:

 ```
  perInstanceProperties: [{
    'name': 'tt-fd3c19b9-f1ab-4354-8dbd-903bb7334b0b-1',
},
{
    'name': 'tt-fd3c19b9-f1ab-4354-8dbd-903bb7334b0b-2'
  }]
```
I referenced documentation [here](https://cloud.google.com/compute/docs/reference/rest/v1/instances/bulkInsert), please reopen if this doesn't work for you.
