### ISSUE TITLE
Error: Cannot build HTTP request for {}, method: List

### ISSUE THREAD

**Issue by loganmzz** [googleapis/nodejs-compute#855]
#### Environment details

  - OS: `Linux Ubuntu`
  - Node.js version: `16.17.1` (LTS)
  - npm version: `8.15.0`
  - `@google-cloud/compute` version: `3.5.0` (latest)

#### Steps to reproduce

  1. `package.json`

```json
{
  "name": "myapp",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "@google-cloud/compute": "3.5.0"
  }
}
```

 2. `index.js`

```js
(async () => {
    try {
        const compute = require('@google-cloud/compute');
        const client = new compute.InstancesClient({
            projectId: process.env.MYAPP_GCLOUD_PROJECT_ID,
            credentials: {
                client_email: process.env.MYAPP_GCLOUD_CREDENTIAL_EMAIL,
                private_key: process.env.MYAPP_GCLOUD_CREDENTIAL_PRIVATE_KEY
            },
        });
        const [vms] = await client.list();
        console.log(vms.map(vm => vm.name));
    } catch (e) {
        console.error('Error with Google Cloud Client Instance', e);
    }
})();
```

  3. `npm i && node index.js`

```text
Error with Google Cloud Client Instance Error: Cannot build HTTP request for {}, method: List
    at encodeRequest (/myapp/node_modules/google-gax/build/src/fallbackRest.js:44:15)
    at Object.serviceStub.<computed> [as list] (/myapp/node_modules/google-gax/build/src/fallbackServiceStub.js:42:35)
    at /myapp/node_modules/@google-cloud/compute/build/src/v1/instances_client.js:225:29
    at wrappedCall (/myapp/node_modules/google-gax/build/src/paginationCalls/pagedApiCaller.js:86:20)
    at Immediate.<anonymous> (/myapp/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16)
    at processImmediate (node:internal/timers:468:21)
```

**Comment by loganmzz** [comment]
Tried with `google-gax` at `3.0.1` (declared dependency) :

```text
Error with Google Cloud Client Instance Error: Cannot find module 'google-gax/build/src/protobuf'
Require stack:
- /myapp/node_modules/@google-cloud/compute/build/protos/protos.js
- /myapp/node_modules/@google-cloud/compute/build/src/index.js
- /myapp/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /myapp/node_modules/@google-cloud/compute/build/protos/protos.js:22:34
    at Object.<anonymous> (/myapp/node_modules/@google-cloud/compute/build/protos/protos.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/myapp/node_modules/@google-cloud/compute/build/protos/protos.js',
    '/myapp/node_modules/@google-cloud/compute/build/src/index.js',
    '/myapp/index.js'
  ]
}
```

**Comment by loganmzz** [comment]
Same with `3.0.3`, `3.1.4` and `3.2.2`

**Comment by loganmzz** [comment]
With `3.3.1`:

```text
Error with Google Cloud Client Instance GoogleError: Required field project is not present in the request.
    at transcode (/myapp/node_modules/google-gax/build/src/transcoding.js:247:19)
    at encodeRequest (/myapp/node_modules/google-gax/build/src/fallbackRest.js:40:52)
    at Object.serviceStub.<computed> [as list] (/myapp/node_modules/google-gax/build/src/fallbackServiceStub.js:42:35)
    at /myapp/node_modules/@google-cloud/compute/build/src/v1/instances_client.js:225:29
    at wrappedCall (/myapp/node_modules/google-gax/build/src/paginationCalls/pagedApiCaller.js:86:20)
    at Immediate.<anonymous> (/myapp/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16)
    at processImmediate (node:internal/timers:468:21)
```
